language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

branches:
  only:
    - master

# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"

# run tests
script: 
  - "nosetests --with-coverage --cover-package=quora"

after_failure:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - bash <(curl -s https://codecov.io/bash)

# email notifications
notifications:
  email:
    on_success: never
    on_failure: never