version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get install zip unzip
            wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo cp chromedriver /usr/local/bin/chromedriver
            sudo chown root /usr/loca/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            sudo chmod 755 /usr/local/bin/chromedriver
            sudo apt-get install -y libglib2.0-0=2.50.3-2 \
                libnss3=2:3.26.2-1.1+deb9u1 \
                libgconf-2-4=3.2.6-4+b1 \
                libfontconfig1=2.11.0-6.7+b1
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python tests.py
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1